### ISSUE TITLE
run example server panic

### ISSUE THREAD

**Issue by zhaoxuat** [datenlord/async-rdma#101]
I use the command-server example. It looks None for the value `imm" and can't unwrap.
```
/data/async-rdma$ RUST_BACKTRACE=1 cargo run --example server localhost 9527
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/server localhost 9527`
server start
accepted
[1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1], None
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/server.rs:32:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
   3: core::option::Option<T>::unwrap
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:823:21
   4: server::receive_data_with_imm_from_client::{{closure}}
             at ./examples/server.rs:32:23
   5: server::main::{{closure}}
             at ./examples/server.rs:103:45
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/park.rs:283:63
   7: tokio::runtime::coop::with_budget
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/coop.rs:73:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/park.rs:283:31
  10: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/context.rs:315:13
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/scheduler/multi_thread/mod.rs:66:9
  12: tokio::runtime::runtime::Runtime::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/runtime.rs:304:45
  13: server::main


/data/async-rdma$ RUST_BACKTRACE=1 cargo run --example client localhost 9527
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/client localhost 9527`
client start
connected
[0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 2, 2, 2, 2]
^[[A^[[A^[[A^[[Athread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: TimedOut, error: "Timeout for waiting for a response." }', examples/client.rs:134:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1112:23
   4: client::main::{{closure}}
             at ./examples/client.rs:134:5
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at /home/zhaoxu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.28.1/src/runtime/runtime.rs:304:45
  12: client::main
             at ./examples/client.rs:141:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by GTwhy** [comment]
Hi @zhaoxuat ,
May I ask what RDMA device you are using? 
The value of immediate data flag may be different on RDMA devices. And you can change this flag by [this API](https://github.com/datenlord/async-rdma/blob/39e26c6cf0317229a0b7dbc557b0f6fe2824ec7b/src/lib.rs#L1009) to adapt their devices.

**Comment by zhaoxuat** [comment]
> Hi @zhaoxuat , May I ask what RDMA device you are using? The value of immediate data flag may be different on RDMA devices. And you can change this flag by [this API](https://github.com/datenlord/async-rdma/blob/39e26c6cf0317229a0b7dbc557b0f6fe2824ec7b/src/lib.rs#L1009) to adapt your devices.

I modify code, it does work well.
https://github.com/datenlord/async-rdma/blob/39e26c6cf0317229a0b7dbc557b0f6fe2824ec7b/examples/server.rs#L100
`let mut rdma = RdmaBuilder::default().set_imm_flag_in_wc(2).unwrap().listen(addr).await.unwrap();`

ib info
```
Infiniband device 'mlx5_0' port 1 status:
	default gid:	 fe80:0000:0000:0000:8a66:64ff:fe7b:b19d
	base lid:	 0x0
	sm lid:		 0x0
	state:		 4: ACTIVE
	phys state:	 5: LinkUp
	rate:		 50 Gb/sec (1X HDR)
	link_layer:	 Ethernet
```

**Comment by GTwhy** [comment]
Thank you for your feedback. In the future, We may consider automatically detecting these devices and setting the corresponding flags. For now, we have simply improved the prompts, but manual operation is still required.
