### ISSUE TITLE
Failed to run example on ubuntu server 20.04

### ISSUE THREAD

**Issue by skyao** [datenlord/async-rdma#115]
I tried to run the example as show in repo index page like:

```bash
cargo run --example rpc
```

```bash
cargo run --example rpc
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/examples/rpc`
rpc server started
2023-08-21T15:50:53.641480Z ERROR async_rdma::error_utilities: OS error Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
2023-08-21T15:50:53.641514Z ERROR async_rdma::error_utilities: OS error Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
Invalid argument (os error 22)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', examples/rpc.rs:147:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', examples/rpc.rs:32:71
```

And I also run this example in another ubuntu 22.04 machine, and it succeed!

**Comment by GTwhy** [comment]
Hi @skyao .
It seems to be a problem related to RDMA devices.
You can run the command `ibv_devinfo`  and then reply with the returned information here.
